apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - name: jenkins-demo-container
        image: hariharanslab/jenkins-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

